language: node_js
node_js:
- '9'
before_install:
- npm install
script:
- npm run build
after_success:
- bash .deploy.sh
branches:
  only: master
env:
  global:
    secure: lyy9+onA0ozvikfeY1Vz1t4uyaoz1c8yrzaUrQy8qmAkG7i7VZJWJEZLXIwqLzwIjNSkuZo9p9h8nlRmbQJW1GxvDS2E4fnNDm7KgvRwwwSG8Ochn17rdqdDDrMRHS9wtmsGVrVWwj5Iic4HJiW7EZ9LZn+hzV0CRUEfl7LjRjhF8NfXN5IvSzhx/MAhgzo6fMuwTJe1kt4h3AbP//M1MyVRJ87nNg7O6NDFvi6lFMmPTSNeUTjgM46bJCmhnt/RSzh7W5TRlwPqpi9RKENNEtBXzIHZLEFMXdwZKUg9SR80zIrCfMxkhVAeIrjQUyW2SzgGcVxZp/9hNiSiljI1SVRdgxf/eKzbifL7J8ZdhXEh0w271xbZEzDbWlat85JYVqsarqNO//cCwzrtMzez2gGR98k+7dAWlAoupWKtW0GLebPnKwkDpYyO5dCW2XozBgsTCugZM7lYrCMsEyxzoClrwsPl+wp026ppd8/wGPI2f3nhRqc9SN0HHmD6vixYxkBvB7dnBT3r5JU8iGfDP4YZVIK8z8F2M3uZwbnl20YIJ4HyIoIL9+MKDwmEtyI9v/KF/OmZLX+FIfcpZ8RURjfN7ZPcfOue2LPTQ1z1Yfw6d1GRqXCeMdenlZiu966eSjx9IazPr7jEUG8x5FIZn/+fbjDMbQJTMqs/d0vp8Zc=
